/polar/det/setWorldFile physWorldBox.gdml
/polar/det/setVolumes module
/polar/det/setVolumes detector

/run/initialize
/polar/Analysis/setThreshold  5 keV
/polar/Analysis/setMCThreshold 10 keV
#pattern

#/polar/Analysis/setMCThreshold 10
#/polar/Analysis/setPreS 1
#/polar/Analysis/setPreC 1
/polar/Analysis/realSim 1
/polar/Analysis/setCalibrationFileName expdata/threshold_00840_method_2_keV.root
#trigger
/polar/setGunType GRB


#https://gcn.gsfc.nasa.gov/other/170114A.gcn3

/polar/GRB/setAlpha  -0.84
/polar/GRB/setBeta -1.99
/polar/GRB/setEpeak 237 keV
/polar/GRB/setEmin 8 keV
/polar/GRB/setEmax 10000 keV
/polar/GRB/setSphRad  300 cm
/polar/GRB/setCircRad 40 cm
/polar/GRB/setPolAng 0 degree
#polarization angle
/polar/GRB/setPolFrac 1  
#polarization degree
/polar/GRB/setTheta 26.4 degree
#polarization theta
/polar/GRB/setPhi 4.9 degree
#polarization theta
/polar/GRB/setFlux 25
/polar/GRB/setFluxEmin 10 keV
/polar/GRB/setFluxEmax 1000 keV

/run/beamOn 2000000
