
# reading Geometry from File
/polar/det/setWorldFile physWorldBox.gdml
/polar/det/setVolumes module
/polar/det/setVolumes detector
#/polar/Analysis/setOutputFileName  analysis_test.root
/polar/Analysis/setThreshold  5 keV
/polar/Analysis/setkB  0.143
/polar/Analysis/setAnalysisLevel  4
/polar/Analysis/setQuickLook 2


/polar/Analysis/setCalibrationFileName  data/response.root

#/polar/det/setVolumes spaceLab
/run/initialize
#/polar/readParticleFrom  proton.root
/polar/setGuneType root
/polar/readParticleFrom  input.root

/run/beamOn 200000
