/polar/det/setWorldFile physWorldBox.gdml
/polar/det/setVolumes module
/polar/det/setVolumes detector

/run/initialize


/vis/scene/create

#/vis/open OGL
#/vis/open OGL 800x800-0+0
#use qt
/vis/open OGLSQt

#
# Use this open statement to create an OpenInventor view:
#/vis/open OIX
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#/vis/open RayTracer
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90 0.
#
# Specify zoom value:
/vis/viewer/zoom 1 
#
# Specify style (surface, wireframe, auxiliary edges,...)
#/vis/viewer/set/style wireframe
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 20 mm
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 1
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#/vis/scene/endOfEventAction refresh
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
/vis/scene/add/axes  0 0 0 40 cm

/polar/Analysis/setThreshold  5 keV
/polar/Analysis/setMCThreshold 10 keV
#pattern

#/polar/Analysis/setMCThreshold 10
#/polar/Analysis/realSim false
#/polar/Analysis/setPreS 1
#/polar/Analysis/setPreC 1
#/polar/Analysis/setCalibrationFileName response.root
#trigger
/polar/setGunType GRB

/polar/GRB/setAlpha  -0.28
/polar/GRB/setBeta -2.55
/polar/GRB/setEpeak 341 keV
/polar/GRB/setEmin 8 keV
/polar/GRB/setEmax 4000 keV
/polar/GRB/setSphRad  100 cm
/polar/GRB/setCircRad 30 cm
/polar/GRB/setPolAng 0 degree
/polar/GRB/setPolFrac 1.0  
/polar/GRB/setTheta 19.5 degree
/polar/GRB/setPhi 148.7 degree

/run/beamOn 100
