

# reading Geometry from File
/polar/det/setWorldFile physWorldBox.gdml
/polar/det/setVolumes module
/polar/det/setVolumes detector

/polar/det/setVolumes spaceLab
/run/initialize

/vis/scene/create
/vis/open VRML2FILE
#/vis/open OGLSQt



/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
/vis/drawVolume
#
/vis/viewer/set/viewpointThetaPhi 90 0.
#
/vis/viewer/zoom 1 
#
/vis/scene/add/axes 0 0 0 1000 mm
/vis/viewer/set/style wireframe
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
# Draw hits at end of event:
/vis/scene/add/hits
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#/vis/scene/endOfEventAction refresh
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#

/polar/Analysis/setThreshold  5 keV
/polar/Analysis/setMCThreshold 10 keV
/polar/Analysis/realSim 1
/polar/Analysis/setCalibrationFileName expdata/threshold_00840_method_2_keV.root
#pattern

/polar/Analysis/setPreS 256
/polar/Analysis/setPreC 256
#trigger
/polar/setGunType GRB

/polar/GRB/setAlpha  -0.28
/polar/GRB/setBeta -2.55
/polar/GRB/setEpeak 341 keV
/polar/GRB/setEmin 8 keV
/polar/GRB/setEmax 10000 keV
/polar/GRB/setSphRad  100 cm
/polar/GRB/setCircRad 30 cm
/polar/GRB/setPolAng 0 degree
#polarization angle
/polar/GRB/setPolFrac 0  
#polarization degree
/polar/GRB/setTheta 0 degree
#polarization theta
/polar/GRB/setPhi 18.7 degree
#polarization theta

/polar/GRB/setFlux 57
/polar/GRB/setFluxEmin 10 keV
/polar/GRB/setFluxEmax 1000 keV

/run/beamOn 16
